# Generated by Django 3.0.6 on 2020-05-22 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo_edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoedad', models.CharField(max_length=30)),
                ('franjaedad', models.CharField(default=0, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pictos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(max_length=500)),
                ('grupo_edad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Grupo_edad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_estructura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3)),
                ('descripcion', models.TextField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('first', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Pregunta')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Test')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_estructura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Tipo_estructura'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Tipo_pregunta'),
        ),
        migrations.CreateModel(
            name='PictosQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('picto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Pictos')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Pregunta')),
            ],
        ),
    ]
