# Generated by Django 3.0.6 on 2020-05-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='first',
            field=models.IntegerField(null=True),
        ),
    ]
