# Generated by Django 3.0.6 on 2020-05-22 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('email_colegio', models.EmailField(blank=True, max_length=254, verbose_name='email address colegio')),
                ('username', models.CharField(blank=True, max_length=255, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=30, verbose_name='nombre')),
                ('apellidos', models.CharField(blank=True, max_length=60, verbose_name='apellidos')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('alias', models.CharField(blank=True, max_length=30)),
                ('DNI', models.CharField(blank=True, max_length=10)),
                ('colegio', models.CharField(max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('validado', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', usuarios.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='User_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.ManyToManyField(related_name='tests', through='usuarios.User_test', to='cuestionarios.Test'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
